### ISSUE TITLE
Env Variables are not working on fresh v1.4.3

### ISSUE THREAD

**Issue by diecodev** [denoland/fresh#1751]
In the current latest version of Fresh, the env vars are not loading automatically from .env file as docs says it should load it.

### IMG OF ERROR
![image](https://github.com/denoland/fresh/assets/51871681/c0caa994-dc42-4cec-8960-7a7d271229e4)

### ENV FILE
![image](https://github.com/denoland/fresh/assets/51871681/25ba89b2-4330-450c-95d2-2282eeac11d4)

**Comment by chillax** [comment]
Bumped into this after upgrading from `fresh@1.4.2` to `fresh@1.4.3` using `deno run -A -r https://fresh.deno.dev/update .` today.

After quickly comparing my project (initially created with `fresh@1.1.6`) with a new project created with `deno run -A -r https://fresh.deno.dev` I noticed that a few lines were missing from my config.

Applying these changes seems to have resolved my issues.

**dev.ts**
```diff
@@ -1,5 +1,8 @@
 #!/usr/bin/env -S deno run -A --watch=static/,routes/
 
 import dev from "$fresh/dev.ts";
+import config from "./fresh.config.ts";
 
-await dev(import.meta.url, "./main.ts");
+import "$std/dotenv/load.ts";
+
+await dev(import.meta.url, "./main.ts", config);
```

**fresh.config.ts**
```diff
@@ -0,0 +1,3 @@
+import { defineConfig } from "$fresh/server.ts";
+
+export default defineConfig({});
```

**Comment by marvinhagemeister** [comment]
This is resolved by #1764

**Comment by diecodev** [comment]
this bug still happens in the current version: 1.5.1

### Image of terminal + code:
![image](https://github.com/denoland/fresh/assets/51871681/8b4a0235-ff42-4670-9304-a915de58ed0c)

**Comment by marvinhagemeister** [comment]
Re-opening, so that his doesn't get lost in GitHub notifications. Any comments on closed issues are barely visible and easily drowned by all other activity. I'll take a look tomorrow.

**Comment by deer** [comment]
Hey @diecodev, can you please provide some more instructions on this one? I initialized a new project with fresh 1.5.2 and applied the following patch:
```diff
diff --git a/dev.ts b/dev.ts
index ae73946..569ffe7 100755
--- a/dev.ts
+++ b/dev.ts
@@ -4,5 +4,7 @@ import dev from "$fresh/dev.ts";
 import config from "./fresh.config.ts";

 import "$std/dotenv/load.ts";
+console.log("from dev.ts");
+console.log({ DB_NAME: Deno.env.get("DB_NAME") });

 await dev(import.meta.url, "./main.ts", config);
diff --git a/routes/index.tsx b/routes/index.tsx
index fc8061e..264129f 100644
--- a/routes/index.tsx
+++ b/routes/index.tsx
@@ -3,6 +3,8 @@ import Counter from "../islands/Counter.tsx";

 export default function Home() {
   const count = useSignal(3);
+  console.log("from index");
+  console.log({ DB_NAME: Deno.env.get("DB_NAME") });
   return (
     <div class="px-4 py-8 mx-auto bg-[#86efac]">
       <div class="max-w-screen-md mx-auto flex flex-col items-center justify-center">
```

I also have a `.env` file with the following content:
```env
DB_NAME=asdf
```

When I do `deno task start` and navigate to `localhost:8000` I see the following output in my console:
```
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
from dev.ts
{ DB_NAME: "asdf" }
The manifest has been generated for 5 routes and 1 islands.

 🍋 Fresh ready
    Local: http://localhost:8000/

from index
{ DB_NAME: "asdf" }
```

Seems to be working for me. Am I doing something wrong or different than you are?

**Comment by diecodev** [comment]
@deer Sorry, in the previous major version (1.4.x) the line ```import "$std/dotenv/load.ts";```` in the `dev.ts` file was missing, that was the problem I had. I just add that piece of code to the file and it works as expected
