### ISSUE TITLE
Strange Errors On Start

### ISSUE THREAD

**Issue by mcgear** [denoland/fresh#1856]
This just randomly started showing up when I run my fresh site, i'm not sure where to start.  

It seems to have something to do with the NPM packages being used by some supporting deno modules.

Looking for some guidance on how to get some better information as to what may be going on:
![image](https://github.com/denoland/fresh/assets/1460046/95c3b3db-801b-4a31-b918-e1fe30c0500b)

This is happening from our repo:
https://github.com/fathym-deno/community-chat

Specifically on our feature/hookups branch

**Comment by mcgear** [comment]
With a little more digging, it seems to only happen on pages that include Islands

**Comment by mcgear** [comment]
I worked around the issue by removing the code referencing that npm package (as i wasn't using it).  that is in a new branch feature/rework.  The feature/hookups branch should still be broken.

**Comment by marvinhagemeister** [comment]
This is caused by a bug in the esbuild deno loader that fails to create the proper directory structure if a scoped npm package is used:

- `npm:foo` -> works
- `npm:@foo/bar` -> triggers bug
 
I fixed that yesterday with https://github.com/denoland/fresh/pull/1841 .

**Comment by mcgear** [comment]
Oh nice, so this should be fixed in the next fresh release?  Thanks for the information

**Comment by quick007** [comment]
Experiencing similar issues as well!

**Comment by marvinhagemeister** [comment]
@mcgear @quick007 Fresh 1.5 is out now. Is the issue still present for you two?

**Comment by quick007** [comment]
seems to be fixed on my end

**Comment by marvinhagemeister** [comment]
Great to hear that. I'm closing this one for now. If any new issues pop up we can just open a new one.
