### ISSUE TITLE
bug: JSR frontend site doesn't work once upgraded to `jsr:@fresh/core@^2.0.0-alpha.34`

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#3006]
`/`, `/@std` and `/docs` all serve blank pages with no indication as to why a blank page has been served. The following is served.

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <html lang="en">
      <head></head>
      <body></body>
    </html>
  </body>
</html>
```

Blocking https://github.com/jsr-io/jsr/pull/1111

**Comment by marvinhagemeister** [comment]
This was caused by a bug in Deno itself (addressed in 2.4.0 or newer). I can't find the particular PR at the moment, but it had to do with Deno not de-duplicating dependencies correctly. This lead to multiple copies of Preact being loaded which in turn meant one portion was rendering the app wrapper and another instance was rendering the page and neither knew of each other.

To resolve this, upgrade Deno to 2.4.0 or newer. Going with a newer Fresh version might also be worth it to benefit from https://github.com/denoland/fresh/pull/3034

**Comment by iuioiua** [comment]
I attempted this again after upgrading to Deno 2.4.1 and I'm still getting the same behaviour.

**Comment by marvinhagemeister** [comment]
Can you link a branch? (note that the lockfile might need to be re-created, the fix didn't involve migrating broken lockfiles)

**Comment by iuioiua** [comment]
Yep, I regenerated the lockfile too. https://github.com/iuioiua/jsr/tree/fresh-alpha-37

**Comment by evanleck** [comment]
Whoop, right after posting the below I tried removing my lock file and re-running `deno install` and now everything works! Please disregard :) and thank you!

---

I'm seeing something similar in a local app I just started tinkering with: nested `<html>` elements and none of the content that I'd expect in the markup. I have log statements in the index function and the app wrapper that both execute, so the code is getting called but the content doesn't seem to reach the browser.
