### ISSUE TITLE
type checking unstable doesn't work with fresh

### ISSUE THREAD

**Issue by sigmaSd** [denoland/fresh#822]
to reproduce:

-  `deno run -r -A https://fresh.deno.dev  bugg`
- `cd  bugg`
- `echo "Deno.serve() >> routes/api/joke.ts` # or any unstable API
- `deno run -A --unstable --check main.ts`

![image](https://user-images.githubusercontent.com/22427111/194389406-0c6df40b-b062-4c26-a5ee-97f097c14433.png)

It works with normal deno projects, it seems to only fail with fresh somehow

```
deno 1.26.0+a6618dc (canary, x86_64-unknown-linux-gnu)
v8 10.7.193.3
typescript 4.8.3
```

**Comment by chibat** [comment]
By adding the following code to main.ts, it worked fine.
```
/// <reference lib="deno.unstable" />
```
But `Deno.spawn` was deleted.

**Comment by sigmaSd** [comment]
I changed the instructions to use another unstable API

thanks for the workaround

**Comment by marvinhagemeister** [comment]
I'm unable to reproduce this issue anymore. Maybe it got fixed in the deno language server?

**Comment by sigmaSd** [comment]
Weird I still get the same error (using the above reproduction steps)
![image](https://github.com/denoland/fresh/assets/22427111/616ca390-9c39-477d-b757-b0a091f09b55)

deno 1.34.1
linux

**Comment by iuioiua** [comment]
I'm able to reproduce this behaviour. My question is whether this behaviour is expected or not. I'll look into this when I can.

**Comment by marvinhagemeister** [comment]
Looks like this is resolved. I can't reproduce this anymore in Deno 2.3.1.
